"use client";

import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-gray-100">
      {/* Header */}

     
      {/* <p className="text-gray-600 mt-2">
        Last updated: {new Date().toLocaleDateString()}
      </p> */}

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 md:p-8 space-y-8">
          {/* Interpretation and Definitions */}
          <section>
             <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-4 ">
                Privacy Policy
            </h1>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Interpretation and Definitions
            </h2>

            <div className="space-y-6">
              <div>
                <h3 className="text-xl font-medium text-gray-800 mb-3">
                  Interpretation
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  Words capitalized have defined meanings under these
                  conditions. They apply regardless of whether in singular or
                  plural form.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-medium text-gray-800 mb-3">
                  Definitions
                </h3>
                <p className="text-gray-600 leading-relaxed mb-4">
                  For the purposes herein:
                </p>

                <div className="space-y-3">
                  {[
                    {
                      term: "Account",
                      definition:
                        "Your unique access to our Service, which may include registration and authentication credentials.",
                    },
                    {
                      term: "Affiliate",
                      definition:
                        'Any entity that controls, is controlled by, or is under common control with the Company, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.',
                    },
                    {
                      term: "Company",
                      definition:
                        'Aam Pannaa Creations LLP (referred to as "the Company", "We", "Us" or "Our").',
                    },
                    {
                      term: "Cookies",
                      definition:
                        "Small files placed on Your device by a website, containing browsing history details and other information.",
                    },
                    {
                      term: "Country",
                      definition: "Refers to the jurisdiction of India.",
                    },
                    {
                      term: "Device",
                      definition:
                        "Any device that can access the Service, such as a computer, smartphone, tablet, or other digital device.",
                    },
                    {
                      term: "Personal Data",
                      definition:
                        "Any information that relates to an identified or identifiable individual, including but not limited to name, email address, phone number, and usage data.",
                    },
                    {
                      term: "Service",
                      definition:
                        "The Aam Panna website and associated services provided by Aam Pannaa Creations LLP.",
                    },
                    {
                      term: "Service Provider",
                      definition:
                        "Any natural or legal person who processes data on behalf of the Company, including third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on behalf of the Company, or assist the Company in analyzing how the Service is used.",
                    },
                    {
                      term: "Usage Data",
                      definition:
                        "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit, pages visited, IP address).",
                    },
                    {
                      term: "Website",
                      definition:
                        "Aam Panna, accessible at",
                        link: "https://www.aampanna.net/"
                    },
                    {
                      term: "You",
                      definition:
                        "The individual accessing or using the Service, or the legal entity on whose behalf such individual is accessing or using the Service.",
                    },
                  ].map((item, index) => (
                    <div key={index} className="bg-gray-50 rounded-lg p-4">
                      <dt className="font-semibold text-gray-800 mb-1">
                        {item.term}:
                      </dt>
                      <dd className="text-gray-600 text-sm leading-relaxed">
                        {item.definition} <a href={item.link} className="text-blue-500 hover:underline">{item.link}</a>
                      </dd>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </section>

          {/* Collecting and Using Your Personal Data */}
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Collecting and Using Your Personal Data
            </h2>

            <div className="space-y-6">
              <div>
                <h3 className="text-xl font-medium text-gray-800 mb-3">
                  Types of Data Collected
                </h3>

                <div className="space-y-4">
                  <div>
                    <h4 className="text-lg font-medium text-gray-800 mb-2">
                      Personal Data
                    </h4>
                    <p className="text-gray-600 leading-relaxed mb-3">
                      During Your use of Our Service, We may collect the
                      following types of Personal Data:
                    </p>
                    <ul className="list-disc list-inside text-gray-600 space-y-1 ml-4">
                      <li>Email address</li>
                      <li>First name and last name</li>
                      <li>Phone number</li>
                      <li>Usage Data</li>
                    </ul>
                  </div>

                  <div>
                    <h4 className="text-lg font-medium text-gray-800 mb-2">
                      Usage Data
                    </h4>
                    <p className="text-gray-600 leading-relaxed mb-3">
                      {`We may also collect information on how the Service is
                      accessed and used ("Usage Data"). This Usage Data may
                      include information such as Your computer's Internet
                      Protocol address (e.g., IP address), browser type, browser
                      version, the pages of our Service that You visit, the time
                      and date of Your visit, the time spent on those pages,
                      unique device identifiers, and other diagnostic data.`}
                    </p>
                    <p className="text-gray-600 leading-relaxed mb-3">
                      {`When You access the Service by or through a mobile device,
                      We may collect certain information automatically,
                      including, but not limited to, the type of mobile device
                      You use, Your mobile device unique ID, the IP address of
                      Your mobile device, Your mobile operating system, the type
                      of mobile Internet browser You use, unique device
                      identifiers, and other diagnostic data.`}
                    </p>
                    <p className="text-gray-600 leading-relaxed">
                      {`We may also collect information that Your browser sends
                      whenever You visit our Service or when You access the
                      Service by or through a mobile device.`}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Tracking Technologies and Cookies */}
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Tracking Technologies and Cookies
            </h2>

            <p className="text-gray-600 leading-relaxed mb-4">
              We use Cookies and similar tracking technologies to track the
              activity on Our Service and store certain information. Tracking
              technologies used are beacons, tags, and scripts to collect and
              track information and to improve and analyze Our Service.
            </p>

            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-medium text-gray-800 mb-3">
                  Types of Cookies Used
                </h3>
                <div className="space-y-3">
                  <div className="bg-blue-50 rounded-lg p-4">
                    <h4 className="font-semibold text-gray-800 mb-1">
                      Session Cookies:
                    </h4>
                    <p className="text-gray-600 text-sm">
                      These are essential for the operation of our Service and
                      expire when You close Your browser.
                    </p>
                  </div>
                  <div className="bg-green-50 rounded-lg p-4">
                    <h4 className="font-semibold text-gray-800 mb-1">
                      Persistent Cookies:
                    </h4>
                    <p className="text-gray-600 text-sm">
                      These remain on Your device for a set period or until You
                      delete them. They help us recognize You as a returning
                      visitor to our Website.
                    </p>
                  </div>
                </div>
              </div>

              <div>
                <h3 className="text-xl font-medium text-gray-800 mb-3">
                  Purpose of Using Cookies
                </h3>
                <div className="space-y-3">
                  <div className="bg-orange-50 rounded-lg p-4">
                    <h4 className="font-semibold text-gray-800 mb-1">
                      Necessary / Essential Cookies:
                    </h4>
                    <p className="text-gray-600 text-sm">
                      These Cookies are necessary for the proper functioning of
                      the Website and to provide the Service requested by You.
                    </p>
                  </div>
                  <div className="bg-purple-50 rounded-lg p-4">
                    <h4 className="font-semibold text-gray-800 mb-1">
                      Functionality Cookies:
                    </h4>
                    <p className="text-gray-600 text-sm">
                      These Cookies allow us to remember choices You make when
                      You use the Website, such as remembering your login
                      details or language preference.
                    </p>
                  </div>
                  <div className="bg-pink-50 rounded-lg p-4">
                    <h4 className="font-semibold text-gray-800 mb-1">
                      Analytics and Performance Cookies:
                    </h4>
                    <p className="text-gray-600 text-sm">
                      These Cookies allow us to analyze how users interact with
                      our Website, so we can improve the functionality and user
                      experience.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mt-4">
              <p className="text-gray-700 text-sm">
                You can instruct Your browser to refuse all Cookies or to
                indicate when a Cookie is being sent. However, if You do not
                accept Cookies, You may not be able to use some parts of our
                Service unless You adjust Your browser setting.
              </p>
            </div>
          </section>

          {/* Use of Your Personal Data */}
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Use of Your Personal Data
            </h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              The Company may use Personal Data for the following purposes:
            </p>

            <ul className="list-disc list-inside text-gray-600 space-y-2 ml-4">
              <li>To provide and maintain our Service</li>
              <li>To manage Your Account</li>
              <li>To contact You</li>
              <li>
                To provide You with news, special offers and general information
              </li>
              <li>To manage Your requests</li>
              <li>For business transfers</li>
              <li>
                For other purposes such as data analysis, identifying usage
                trends, etc.
              </li>
            </ul>
          </section>

          {/* Sharing Your Personal Data */}
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Sharing Your Personal Data
            </h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              We may share Your personal information in the following
              situations:
            </p>

            <ul className="list-disc list-inside text-gray-600 space-y-2 ml-4">
              <li>With Service Providers</li>
              <li>For business transfers</li>
              <li>With Affiliates</li>
              <li>With business partners</li>
              <li>With other users</li>
              <li>With Your consent</li>
            </ul>
          </section>

          {/* Disclosure of Your Personal Data */}
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Disclosure of Your Personal Data
            </h2>

            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-medium text-gray-800 mb-3">
                  Business Transactions
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  If the Company is involved in a merger, acquisition, or asset
                  sale, Your Personal Data may be transferred. We will provide
                  notice before Your Personal Data is transferred and becomes
                  subject to a different Privacy Policy.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-medium text-gray-800 mb-3">
                  Law Enforcement
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  Under certain circumstances, the Company may be required to
                  disclose Your Personal Data if required to do so by law or in
                  response to valid requests by public authorities (e.g., a
                  court or a government agency).
                </p>
              </div>

              <div>
                <h3 className="text-xl font-medium text-gray-800 mb-3">
                  Other Legal Requirements
                </h3>
                <p className="text-gray-600 leading-relaxed mb-3">
                  The Company may disclose Your Personal Data in the good faith
                  belief that such action is necessary to:
                </p>
                <ul className="list-disc list-inside text-gray-600 space-y-1 ml-4">
                  <li>Comply with a legal obligation</li>
                  <li>
                    Protect and defend the rights or property of the Company
                  </li>
                  <li>
                    Prevent or investigate possible wrongdoing in connection
                    with the Service
                  </li>
                  <li>
                    Protect the personal safety of Users of the Service or the
                    public
                  </li>
                  <li>Protect against legal liability</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Security of Your Personal Data */}
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Security of Your Personal Data
            </h2>
            <div className="bg-red-50 border-l-4 border-red-400 p-4">
              <p className="text-gray-700 leading-relaxed">
                The security of Your Personal Data is important to Us, but
                remember that no method of transmission over the Internet, or
                method of electronic storage is 100% secure. While We strive to
                use commercially acceptable means to protect Your Personal Data,
                We cannot guarantee its absolute security.
              </p>
            </div>
          </section>

          {/* Your Data Protection Rights */}
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Your Data Protection Rights
            </h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              Depending on Your location, You may have the following rights
              regarding Your Personal Data:
            </p>

            <div className="grid gap-3">
              {[
                {
                  right: "Access",
                  description: "You can request copies of Your Personal Data.",
                },
                {
                  right: "Rectification",
                  description:
                    "You can request that We correct any inaccuracies in Your Personal Data.",
                },
                {
                  right: "Erasure",
                  description:
                    "You can request that We delete Your Personal Data, under certain conditions.",
                },
                {
                  right: "Restrict Processing",
                  description:
                    "You can request that We restrict the processing of Your Personal Data, under certain conditions.",
                },
                {
                  right: "Data Portability",
                  description:
                    "You can request a copy of Your Personal Data in a structured, machine-readable format or have it transferred to another controller.",
                },
                {
                  right: "Object to Processing",
                  description:
                    "You can object to Our processing of Your Personal Data, under certain conditions.",
                },
                {
                  right: "Withdraw Consent",
                  description:
                    "You can withdraw Your consent where We rely on consent to process Your Personal Data.",
                },
              ].map((item, index) => (
                <div key={index} className="bg-gray-50 rounded-lg p-4">
                  <h4 className="font-semibold text-gray-800 mb-1">
                    {item.right}:
                  </h4>
                  <p className="text-gray-600 text-sm">{item.description}</p>
                </div>
              ))}
            </div>

            <div className="bg-blue-50 border-l-4 border-blue-400 p-4 mt-4">
              <p className="text-gray-700 text-sm">
                If You wish to exercise any of these rights, please contact us
                using the contact details provided below.
              </p>
            </div>
          </section>

          {/* Changes to This Privacy Policy */}
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Changes to This Privacy Policy
            </h2>
            <p className="text-gray-600 leading-relaxed mb-3">
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="text-gray-600 leading-relaxed">
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
          </section>

          {/* Contact Us */}
          <section className="bg-gradient-to-r from-orange-50 to-pink-50 rounded-xl p-6 border border-orange-200">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Contact Us
            </h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              If you have any questions about this Privacy Policy, You can
              contact us:
            </p>
            <div className="bg-white rounded-lg p-4 border border-orange-200">
              <p className="text-gray-700">
                <span className="font-semibold">By email:</span>{" "}
                <a
                  href="mailto:Nikitasingh@aampanna.net"
                  className="text-orange-600 hover:text-orange-800 underline"
                >
                  nikitasingh@aampanna.net
                </a>
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
